import { MikroOrmModule } from '@mikro-orm/nestjs';
import { Global, Module } from '@nestjs/common';
import { FarmerRepositoryInjectToken } from '@app/backend-feature-farmer-shared';
import { ProductRepositoryInjectToken } from '@app/backend-feature-product-shared';
import { OrderRepositoryInjectToken } from '@app/backend-feature-order-shared';
import { AgriTechOperationsRepositoryInjectToken } from '@app/backend-feature-agritech-shared';
import {
  MarketplaceRepositoryInjectToken,
  MarketplaceContractLifecycleRepositoryInjectToken,
  MarketplaceContractNotificationRepositoryInjectToken,
  MarketplaceDashboardAiRepositoryInjectToken,
  MarketplaceEngagementRepositoryInjectToken,
  MarketplaceProviderOperationRepositoryInjectToken,
  MarketplacePublicRepositoryInjectToken,
  MarketplacePromotionRepositoryInjectToken,
  MarketplaceVerificationRepositoryInjectToken,
} from '@app/backend-feature-agritech-shared';
import { PaymentRepositoryInjectToken } from '@app/backend-feature-payment-shared';
import {
  AdvisoryEntitySchema,
  AgriTechPartnerEntitySchema,
  DeliveryEntitySchema,
  FarmerEntitySchema,
  FieldVisitEntitySchema,
  IntegrationStateEntitySchema,
  OrderEntitySchema,
  PaymentTransactionEntitySchema,
  PilotCohortEntitySchema,
  ProduceListingEntitySchema,
  ProductEntitySchema,
  BuyerRequestEntitySchema,
  CartEntitySchema,
  ContractEntitySchema,
  RequestOfferEntitySchema,
  MarketplaceLegacyFavoriteArchiveEntitySchema,
  MarketplaceLegacyReviewArchiveEntitySchema,
  MarketplaceLegacySampleRequestArchiveEntitySchema,
  VerificationEntitySchema,
  MarketplaceProviderOperationEntitySchema,
  MarketplaceProduceOrganizationBindingEntitySchema,
  MarketplaceRequestOrganizationBindingEntitySchema,
  MarketplaceListingPublicationEntitySchema,
  MarketplaceListingPromotionEntitySchema,
  MarketplacePartnerMembershipEntitySchema,
  MarketplaceCommerceOperationEntitySchema,
  MarketplacePublicationModerationOperationEntitySchema,
  MarketplacePublicSellerEntitySchema,
  MarketplacePublicSellerRevisionEntitySchema,
  MarketplaceRequestPublicationEntitySchema,
  VerificationEvidenceEntitySchema,
  MarketplaceContractArtifactEntitySchema,
  MarketplaceContractSignatureEntitySchema,
  MarketplaceContractSettlementEntitySchema,
  MarketplaceContractLifecycleEventEntitySchema,
  MarketplaceContractFulfillmentEntitySchema,
  MarketplaceContractDisputeEntitySchema,
  MarketplaceContractDisputeEvidenceEntitySchema,
  MarketplaceContractDisputeResolutionEvidenceEntitySchema,
  MarketplaceContractReputationSignalEntitySchema,
  MarketplaceContractCommissionEntitySchema,
  MarketplaceContractNotificationIntentEntitySchema,
  MarketplaceContractReviewEligibilityEntitySchema,
  MarketplaceAiConsultationEntitySchema,
  MarketplaceAiConsultationOperationEntitySchema,
  MarketplaceAiStarterCartOperationEntitySchema,
  MarketplaceSamplePolicyEntitySchema,
  MarketplaceSampleMonthlyUsageEntitySchema,
  MarketplaceListingFavoriteEntitySchema,
  MarketplaceListingSampleEntitySchema,
  MarketplaceListingReviewEntitySchema,
  MarketplaceReviewReplyEntitySchema,
  MarketplaceReviewAggregateEntitySchema,
  MarketplaceReviewReportEntitySchema,
  MarketplaceEngagementEventEntitySchema,
  MarketplaceEngagementNotificationIntentEntitySchema,
  MarketplaceEngagementOperationEntitySchema,
} from './entities';
import {
  PostgresAgriTechOperationsRepository,
  PostgresFarmerRepository,
  PostgresMarketplaceRepository,
  PostgresMarketplacePublicRepository,
  PostgresMarketplacePromotionRepository,
  PostgresMarketplaceContractLifecycleRepository,
  PostgresMarketplaceContractNotificationRepository,
  PostgresMarketplaceDashboardAiRepository,
  PostgresMarketplaceEngagementRepository,
  PostgresPaymentRepository,
  PostgresOrderRepository,
  PostgresProductRepository,
} from './repositories';

const repositoryProviders = [
  PostgresFarmerRepository,
  PostgresProductRepository,
  PostgresOrderRepository,
  PostgresAgriTechOperationsRepository,
  PostgresMarketplaceRepository,
  PostgresMarketplacePublicRepository,
  PostgresMarketplacePromotionRepository,
  PostgresMarketplaceContractLifecycleRepository,
  PostgresMarketplaceContractNotificationRepository,
  PostgresMarketplaceDashboardAiRepository,
  PostgresMarketplaceEngagementRepository,
  PostgresPaymentRepository,
  { provide: FarmerRepositoryInjectToken, useExisting: PostgresFarmerRepository },
  { provide: ProductRepositoryInjectToken, useExisting: PostgresProductRepository },
  { provide: OrderRepositoryInjectToken, useExisting: PostgresOrderRepository },
  { provide: AgriTechOperationsRepositoryInjectToken, useExisting: PostgresAgriTechOperationsRepository },
  { provide: MarketplaceRepositoryInjectToken, useExisting: PostgresMarketplaceRepository },
  { provide: MarketplacePublicRepositoryInjectToken, useExisting: PostgresMarketplacePublicRepository },
  { provide: MarketplacePromotionRepositoryInjectToken, useExisting: PostgresMarketplacePromotionRepository },
  {
    provide: MarketplaceContractLifecycleRepositoryInjectToken,
    useExisting: PostgresMarketplaceContractLifecycleRepository,
  },
  {
    provide: MarketplaceContractNotificationRepositoryInjectToken,
    useExisting: PostgresMarketplaceContractNotificationRepository,
  },
  {
    provide: MarketplaceDashboardAiRepositoryInjectToken,
    useExisting: PostgresMarketplaceDashboardAiRepository,
  },
  {
    provide: MarketplaceEngagementRepositoryInjectToken,
    useExisting: PostgresMarketplaceEngagementRepository,
  },
  { provide: MarketplaceProviderOperationRepositoryInjectToken, useExisting: PostgresMarketplaceRepository },
  { provide: MarketplaceVerificationRepositoryInjectToken, useExisting: PostgresMarketplaceRepository },
  { provide: PaymentRepositoryInjectToken, useExisting: PostgresPaymentRepository },
];

@Global()
@Module({
  imports: [
    MikroOrmModule.forFeature([
      FarmerEntitySchema,
      ProductEntitySchema,
      OrderEntitySchema,
      AgriTechPartnerEntitySchema,
      ProduceListingEntitySchema,
      DeliveryEntitySchema,
      FieldVisitEntitySchema,
      AdvisoryEntitySchema,
      PilotCohortEntitySchema,
      IntegrationStateEntitySchema,
      PaymentTransactionEntitySchema,
      VerificationEntitySchema,
      MarketplaceProviderOperationEntitySchema,
      MarketplaceProduceOrganizationBindingEntitySchema,
      MarketplaceRequestOrganizationBindingEntitySchema,
      MarketplacePublicSellerEntitySchema,
      MarketplacePublicSellerRevisionEntitySchema,
      MarketplaceListingPublicationEntitySchema,
      MarketplaceListingPromotionEntitySchema,
      MarketplacePartnerMembershipEntitySchema,
      MarketplaceCommerceOperationEntitySchema,
      MarketplacePublicationModerationOperationEntitySchema,
      MarketplaceRequestPublicationEntitySchema,
      VerificationEvidenceEntitySchema,
      CartEntitySchema,
      MarketplaceLegacySampleRequestArchiveEntitySchema,
      MarketplaceLegacyFavoriteArchiveEntitySchema,
      MarketplaceLegacyReviewArchiveEntitySchema,
      BuyerRequestEntitySchema,
      RequestOfferEntitySchema,
      ContractEntitySchema,
      MarketplaceContractArtifactEntitySchema,
      MarketplaceContractSignatureEntitySchema,
      MarketplaceContractSettlementEntitySchema,
      MarketplaceContractLifecycleEventEntitySchema,
      MarketplaceContractFulfillmentEntitySchema,
      MarketplaceContractDisputeEntitySchema,
      MarketplaceContractDisputeEvidenceEntitySchema,
      MarketplaceContractDisputeResolutionEvidenceEntitySchema,
      MarketplaceContractReputationSignalEntitySchema,
      MarketplaceContractCommissionEntitySchema,
      MarketplaceContractNotificationIntentEntitySchema,
      MarketplaceContractReviewEligibilityEntitySchema,
      MarketplaceAiConsultationEntitySchema,
      MarketplaceAiConsultationOperationEntitySchema,
      MarketplaceAiStarterCartOperationEntitySchema,
      MarketplaceSamplePolicyEntitySchema,
      MarketplaceSampleMonthlyUsageEntitySchema,
      MarketplaceListingFavoriteEntitySchema,
      MarketplaceListingSampleEntitySchema,
      MarketplaceListingReviewEntitySchema,
      MarketplaceReviewReplyEntitySchema,
      MarketplaceReviewAggregateEntitySchema,
      MarketplaceReviewReportEntitySchema,
      MarketplaceEngagementEventEntitySchema,
      MarketplaceEngagementNotificationIntentEntitySchema,
      MarketplaceEngagementOperationEntitySchema,
    ]),
  ],
  providers: repositoryProviders,
  exports: repositoryProviders,
})
export class AgriTechPostgresModule {}
