// Generated by `pnpm nrb setup`. Do not edit by hand.
import { Global, Module } from '@nestjs/common';
import { RedisModule } from '@app/backend-common-redis';
import { S3Module } from '@app/backend-common-s3';
import { AgriTechMainModule } from '@app/backend-feature-agritech-main';
import { FarmerMainModule } from '@app/backend-feature-farmer-main';
import { NotificationMainModule } from '@app/backend-feature-notification-main';
import { OrderMainModule } from '@app/backend-feature-order-main';
import { PaymentModule } from '@app/backend-feature-payment-main';
import { ProductMainModule } from '@app/backend-feature-product-main';
import { PostgresMainModule } from '@app/backend-postgres-main';
import { AgriTechPostgresModule } from '@app/backend-postgres-main-agritech';
import { AuthPostgresModule } from '@app/backend-postgres-main-auth';
import { FeatureFlagsPostgresModule } from '@app/backend-postgres-main-feature-flags';
import { NotificationPostgresModule } from '@app/backend-postgres-main-notification';

@Global()
@Module({
  imports: [
    AgriTechMainModule,
    AgriTechPostgresModule,
    AuthPostgresModule,
    FarmerMainModule,
    FeatureFlagsPostgresModule,
    NotificationMainModule.forRoot({ enableScheduler: false, exposeHttp: false }),
    NotificationPostgresModule,
    OrderMainModule,
    PaymentModule,
    PostgresMainModule.forRoot(),
    ProductMainModule,
    RedisModule.forRoot(),
    S3Module.forRoot(),
  ],
  exports: [
    AgriTechMainModule,
    AgriTechPostgresModule,
    AuthPostgresModule,
    FarmerMainModule,
    FeatureFlagsPostgresModule,
    NotificationMainModule,
    NotificationPostgresModule,
    OrderMainModule,
    PaymentModule,
    PostgresMainModule,
    ProductMainModule,
    RedisModule,
    S3Module,
  ],
})
export class UserAppApiCapabilitiesModule {}
