import type { Product, ProductCategory } from './product';

/**
 * Demo catalog content, served by the API.
 *
 * A freshly migrated tenant has published nothing, so every discovery surface —
 * shelves, section catalogs, region and category filters, sort, search, product
 * detail — renders as an empty shell. This dataset stands in for that tenant so
 * the marketplace can be explored end to end, and it is delivered through the
 * same `marketplace/catalog` endpoints as real listings: the client receives
 * catalog rows and never carries a copy of them.
 *
 * It is never mixed into live tenant data. `ListProductsUseCase` reaches for it
 * only when the tenant's own catalog comes back empty, and the response marks
 * itself as demo content so the UI can say so.
 *
 * Product names carry the `name`/`nameRu`/`nameUz`/`nameUzCyrl` quartet the
 * catalog stores, so no listing falls back to English in a locale it claims to
 * support, while `description` stays single-language on purpose: it mirrors the
 * seller-authored free-text field, so it is listing content rather than app copy
 * and is deliberately not routed through translation keys.
 */

/** Fixed timestamps keep the dataset deterministic across requests and tests. */
const createdAt = new Date('2026-03-02T08:00:00.000Z');
const updatedAt = new Date('2026-07-28T08:00:00.000Z');

/**
 * Demo rows carry v4-shaped identifiers because the marketplace routes parse
 * product ids as UUIDs. The `dec0de00` prefix marks them as demo content at a
 * glance, and the row’s own `catalogNumber` keeps the id stable between
 * deployments and across insertions elsewhere in the dataset.
 */
const demoProductId = (catalogNumber: number): string =>
  `dec0de00-0000-4000-8000-${String(catalogNumber).padStart(12, '0')}`;

const suppliers = {
  agroKimyo: 'Agro Kimyo Servis',
  andijonUrug: "Andijon Urug'chilik",
  buxoroTaminot: "Buxoro Agro Ta'minot",
  dehqonBozor: 'Dehqon Bozori Kooperativi',
  fargonaDehqon: "Farg'ona Dehqon Kooperativi",
  fargonaTexnika: "Farg'ona Agrotexnika",
  namanganIssiqxona: 'Namangan Issiqxona Servis',
  qashqaSuv: 'Qashqadaryo Suv Tizim',
  samarqandBog: "Samarqand Bog'dorchilik",
  sirdaryoDon: 'Sirdaryo Don Terminali',
  surxonMeva: 'Surxon Meva Savdo',
  toshkentAgroservis: 'Toshkent Agroservis Markazi',
  xorazmDehqon: 'Xorazm Dehqon Kooperativi',
  xorazmHosil: 'Xorazm Hosil Eksport',
} as const;

/**
 * Where the demo photographs are served from. They are checked into the user
 * app's `public/` tree and referenced by root-relative path on purpose: every
 * deployment sends `img-src 'self' data:`, so a remote photo host would be
 * blocked in the browser even though it resolves in a dev server.
 *
 * The `/media/` prefix is deliberate. `/marketplace/` is a reserved API
 * namespace — both the Vite dev proxy and `docker/nginx-fullstack.conf` route
 * every path under it to the user API — so an asset parked there answers 404
 * with a problem document instead of an image. Provenance and licences for each
 * file live in `apps/frontend/app/public/media/marketplace/README.md`.
 */
const photo = (name: string): string => `/media/marketplace/${name}.webp`;

interface DemoProductSeed {
  /**
   * The row's permanent catalog number, which `demoProductId` turns into its
   * uuid. Explicit rather than positional: seeded `products`,
   * `marketplace_listing_publications`, demo reviews and demo contracts all
   * address a listing by that uuid, so numbering by array position renumbered
   * every later row the moment one was inserted and orphaned everything already
   * pointing at them. Numbers are never reused.
   */
  catalogNumber: number;
  category: ProductCategory;
  description: string;
  /**
   * Root-relative photographs for the listing, newest-facing first. Kept at most
   * two per row: `marketplace_listing_publications` caps a published snapshot at
   * five assets, and a demo row has no reason to approach that. A few rows carry
   * none on purpose, which keeps the client category illustration exercised
   * against seeded data rather than only against an empty database.
   */
  images: readonly string[];
  name: string;
  nameRu: string;
  nameUz: string;
  nameUzCyrl: string;
  priceUzs: number;
  region: string;
  /**
   * Overrides the category default from `sampleAvailableFor`. Bulk goods a
   * seller cannot split — a screened tonne of manure, a sealed sack of wettable
   * sulphur — decline a sample even though their category usually offers one.
   */
  sampleAvailable?: boolean;
  stockQuantity: number;
  supplier: string;
  unit: string;
}

const seeds: readonly DemoProductSeed[] = [
  {
    catalogNumber: 1,
    category: 'seed',
    description:
      'Гибрид F1 для открытого грунта. Срок вегетации 105–115 дней, устойчив к фузариозу. Партия сертифицирована, всхожесть 96%.',
    images: [photo('cotton-bolls'), photo('cotton-field')],
    name: 'Cotton seed “Omad” F1',
    nameRu: 'Семена хлопка «Омад» F1',
    nameUz: "Paxta urug'i «Omad» F1",
    nameUzCyrl: 'Пахта уруғи «Омад» F1',
    priceUzs: 412_000,
    region: 'Andijon',
    stockQuantity: 480,
    supplier: suppliers.andijonUrug,
    unit: '25 kg',
  },
  {
    catalogNumber: 2,
    category: 'seed',
    description:
      'Озимая пшеница для орошаемых земель Ферганской долины. Урожайность до 7,2 т/га, зимостойкость высокая.',
    images: [photo('winter-wheat-field'), photo('wheat-grain')],
    name: 'Winter wheat “Durdona”',
    nameRu: 'Озимая пшеница «Дурдона»',
    nameUz: "Kuzgi bug'doy «Durdona»",
    nameUzCyrl: 'Кузги буғдой «Дурдона»',
    priceUzs: 268_000,
    region: "Farg'ona",
    stockQuantity: 1_240,
    supplier: suppliers.andijonUrug,
    unit: '50 kg',
  },
  {
    catalogNumber: 3,
    category: 'seed',
    description: 'Ранний томат для теплиц, плод 140–160 г, лежкость 18 дней. Пробная партия доступна бесплатно.',
    images: [photo('tomato-greenhouse'), photo('tomato-fruit')],
    name: 'Tomato “Nurafshon”',
    nameRu: 'Томат «Нурафшон»',
    nameUz: 'Pomidor «Nurafshon»',
    nameUzCyrl: 'Помидор «Нурафшон»',
    priceUzs: 96_500,
    region: 'Toshkent',
    stockQuantity: 320,
    supplier: suppliers.samarqandBog,
    unit: '500 g',
  },
  {
    catalogNumber: 4,
    category: 'seed',
    description: 'Люцерна для сенокоса, 3–4 укоса за сезон. Чистота семян 99,1%, без карантинных сорняков.',
    images: [photo('alfalfa-field')],
    name: 'Alfalfa seed, first reproduction',
    nameRu: 'Семена люцерны, первая репродукция',
    nameUz: "Beda urug'i, birinchi reproduksiya",
    nameUzCyrl: 'Беда уруғи, биринчи репродуксия',
    priceUzs: 184_000,
    region: 'Samarqand',
    stockQuantity: 96,
    supplier: suppliers.andijonUrug,
    unit: '20 kg',
  },
  {
    catalogNumber: 5,
    category: 'fertilizer',
    description: 'Аммофос 12:52, гранулированный. Для основной заправки под хлопок и зерновые.',
    images: [photo('fertilizer-granules')],
    name: 'Ammophos 12:52',
    nameRu: 'Аммофос 12:52',
    nameUz: 'Ammofos 12:52',
    nameUzCyrl: 'Аммофос 12:52',
    priceUzs: 3_150_000,
    region: 'Navoiy',
    stockQuantity: 42,
    supplier: suppliers.agroKimyo,
    unit: '1 t',
  },
  {
    catalogNumber: 6,
    category: 'fertilizer',
    description: 'Карбамид 46% азота, азотная подкормка. Отгрузка со склада в Навои, минимальная партия 1 тонна.',
    images: [photo('fertilizer-spreading')],
    name: 'Urea 46% N',
    nameRu: 'Карбамид 46% N',
    nameUz: 'Karbamid 46% N',
    nameUzCyrl: 'Карбамид 46% N',
    priceUzs: 2_760_000,
    region: 'Navoiy',
    stockQuantity: 88,
    supplier: suppliers.agroKimyo,
    unit: '1 t',
  },
  {
    catalogNumber: 7,
    category: 'pesticide',
    description: 'Системный фунгицид против мучнистой росы на винограде и овощных. Срок ожидания 14 дней.',
    images: [photo('pesticide-spraying')],
    name: 'Systemic fungicide, 5 L',
    nameRu: 'Системный фунгицид, 5 л',
    nameUz: 'Tizimli fungitsid, 5 l',
    nameUzCyrl: 'Тизимли фунгицид, 5 л',
    priceUzs: 428_000,
    region: 'Samarqand',
    stockQuantity: 130,
    supplier: suppliers.agroKimyo,
    unit: '5 l',
  },
  {
    catalogNumber: 20,
    category: 'seed',
    description:
      'Средневолокнистый сорт для Бухарской и Навоийской зон. Всхожесть 94%, обработка от гоммоза выполнена. Партия сертифицирована.',
    images: [photo('cotton-bolls'), photo('cotton-field')],
    name: 'Cotton seed “Bukhoro-102”',
    nameRu: 'Семена хлопка «Бухоро-102»',
    nameUz: "Paxta urug'i «Buxoro-102»",
    nameUzCyrl: 'Пахта уруғи «Бухоро-102»',
    priceUzs: 386_000,
    region: 'Buxoro',
    stockQuantity: 260,
    supplier: suppliers.buxoroTaminot,
    unit: '25 kg',
  },
  {
    catalogNumber: 21,
    category: 'seed',
    description: 'Гибрид на силос и зелёный корм, ФАО 350. Высота растения до 2,8 м, выход зелёной массы 55–60 т/га.',
    images: [photo('maize-cobs')],
    name: 'Maize seed, silage hybrid',
    nameRu: 'Семена кукурузы, силосный гибрид',
    nameUz: "Makkajo'xori urug'i, silos duragayi",
    nameUzCyrl: 'Маккажўхори уруғи, силос дурагайи',
    priceUzs: 322_000,
    region: 'Sirdaryo',
    stockQuantity: 180,
    supplier: suppliers.sirdaryoDon,
    unit: '25 kg',
  },
  {
    catalogNumber: 22,
    category: 'seed',
    description: 'Среднеспелый рис для чекового орошения низовий Амударьи. Чистота 99,2%, влажность 13,5%.',
    images: [photo('rice-paddy')],
    name: 'Rice seed, first reproduction',
    nameRu: 'Семена риса, первая репродукция',
    nameUz: "Sholi urug'i, birinchi reproduksiya",
    nameUzCyrl: 'Шоли уруғи, биринчи репродуксия',
    priceUzs: 246_000,
    region: "Qoraqalpog'iston",
    stockQuantity: 410,
    supplier: suppliers.sirdaryoDon,
    unit: '50 kg',
  },
  {
    catalogNumber: 23,
    category: 'seed',
    description:
      'Озимая пшеница для богарных и полуорошаемых участков. Хлебопекарные качества высокие, устойчивость к бурой ржавчине средняя.',
    images: [photo('winter-wheat-field')],
    name: 'Winter wheat “Bunyodkor”',
    nameRu: 'Озимая пшеница «Бунёдкор»',
    nameUz: "Kuzgi bug'doy «Bunyodkor»",
    nameUzCyrl: 'Кузги буғдой «Бунёдкор»',
    priceUzs: 252_000,
    region: 'Jizzax',
    stockQuantity: 870,
    supplier: suppliers.sirdaryoDon,
    unit: '50 kg',
  },
  {
    catalogNumber: 24,
    category: 'seed',
    description: 'Маш на повторный посев после зерновых. Вегетация 65–75 дней, пригоден для механизированной уборки.',
    images: [photo('mung-beans')],
    name: 'Mung bean seed, second reproduction',
    nameRu: 'Семена маша, вторая репродукция',
    nameUz: "Mosh urug'i, ikkinchi reproduksiya",
    nameUzCyrl: 'Мош уруғи, иккинчи репродуксия',
    priceUzs: 158_000,
    region: "Farg'ona",
    stockQuantity: 210,
    supplier: suppliers.andijonUrug,
    unit: '25 kg',
  },
  {
    catalogNumber: 25,
    category: 'seed',
    description: 'Лук на длительное хранение, вызревание дружное, лежкость до 7 месяцев. Всхожесть 88%.',
    images: [photo('yellow-onions')],
    name: 'Onion seed, yellow storage type',
    nameRu: 'Семена лука репчатого, лежкий жёлтый',
    nameUz: "Piyoz urug'i, sariq saqlanuvchi navi",
    nameUzCyrl: 'Пиёз уруғи, сариқ сақланувчи нави',
    priceUzs: 128_000,
    region: 'Xorazm',
    stockQuantity: 340,
    supplier: suppliers.xorazmHosil,
    unit: '1 kg',
  },
  {
    catalogNumber: 26,
    category: 'seed',
    description: 'Арбуз среднего срока, средняя масса плода 8–11 кг, транспортабельность хорошая.',
    images: [photo('watermelon-field')],
    name: 'Watermelon seed, open field',
    nameRu: 'Семена арбуза для открытого грунта',
    nameUz: "Tarvuz urug'i, ochiq maydon uchun",
    nameUzCyrl: 'Тарвуз уруғи, очиқ майдон учун',
    priceUzs: 74_000,
    region: 'Qashqadaryo',
    stockQuantity: 260,
    supplier: suppliers.samarqandBog,
    unit: '250 g',
  },
  {
    catalogNumber: 27,
    category: 'seed',
    description: 'Морковь сортотипа Флакке для осеннего сбора и зимнего хранения. Корнеплод 18–22 см.',
    images: [photo('carrots')],
    name: 'Carrot seed, storage type',
    nameRu: 'Семена моркови, лежкий тип',
    nameUz: "Sabzi urug'i, saqlanuvchi turi",
    nameUzCyrl: 'Сабзи уруғи, сақланувчи тури',
    priceUzs: 118_000,
    region: 'Toshkent',
    stockQuantity: 190,
    supplier: suppliers.samarqandBog,
    unit: '500 g',
  },
  {
    catalogNumber: 28,
    category: 'seed',
    description:
      'Перец для зимне-весеннего оборота, плод кубовидный 180–220 г. Партия распродана, следующее поступление после уточнения.',
    images: [photo('greenhouse-film')],
    name: 'Sweet pepper seed, greenhouse',
    nameRu: 'Семена перца сладкого для теплиц',
    nameUz: "Bulg'or qalampiri urug'i, issiqxona uchun",
    nameUzCyrl: 'Булғор қалампири уруғи, иссиқхона учун',
    priceUzs: 142_000,
    region: 'Namangan',
    stockQuantity: 0,
    supplier: suppliers.namanganIssiqxona,
    unit: '250 g',
  },
  {
    catalogNumber: 29,
    category: 'fertilizer',
    description: 'Диаммонийфосфат гранулированный, для основного внесения под зерновые и хлопок.',
    images: [photo('fertilizer-granules')],
    name: 'DAP 18:46',
    nameRu: 'Диаммофос 18:46',
    nameUz: 'Diammofos 18:46',
    nameUzCyrl: 'Диаммофос 18:46',
    priceUzs: 3_480_000,
    region: 'Navoiy',
    stockQuantity: 36,
    supplier: suppliers.agroKimyo,
    unit: '1 t',
  },
  {
    catalogNumber: 30,
    category: 'fertilizer',
    description: 'Бесхлорное калийное удобрение для винограда, овощных и плодовых. Мешки 25 кг на паллете.',
    images: [photo('fertilizer-granules')],
    name: 'Potassium sulphate 50% K2O',
    nameRu: 'Сульфат калия 50% K2O',
    nameUz: 'Kaliy sulfat 50% K2O',
    nameUzCyrl: 'Калий сулфат 50% K2O',
    priceUzs: 4_920_000,
    region: 'Buxoro',
    stockQuantity: 24,
    supplier: suppliers.buxoroTaminot,
    unit: '1 t',
  },
  {
    catalogNumber: 31,
    category: 'fertilizer',
    description:
      'Азотная подкормка под зерновые в фазу кущения. Отгрузка со склада в Сырдарье, минимальная партия 1 тонна.',
    images: [photo('fertilizer-spreading')],
    name: 'Ammonium nitrate 34.4% N',
    nameRu: 'Аммиачная селитра 34,4% N',
    nameUz: 'Ammiakli selitra 34,4% N',
    nameUzCyrl: 'Аммиакли селитра 34,4% N',
    priceUzs: 2_940_000,
    region: 'Sirdaryo',
    stockQuantity: 65,
    supplier: suppliers.buxoroTaminot,
    unit: '1 t',
  },
  {
    catalogNumber: 32,
    category: 'fertilizer',
    description: 'Перегной трёхлетнего перепревания, просеянный, без сорняков. Самовывоз, погрузка на месте.',
    images: [],
    name: 'Rotted cattle manure, screened',
    nameRu: 'Перегной, просеянный',
    nameUz: "Chirigan go'ng, elangan",
    nameUzCyrl: 'Чириган гўнг, эланган',
    priceUzs: 620_000,
    region: 'Toshkent',
    sampleAvailable: false,
    stockQuantity: 48,
    supplier: suppliers.dehqonBozor,
    unit: '1 t',
  },
  {
    catalogNumber: 33,
    category: 'pesticide',
    description: 'Контактный инсектицид для обработки хлопка против коробочного червя. Срок ожидания 21 день.',
    images: [photo('pesticide-spraying')],
    name: 'Contact insecticide for cotton bollworm, 5 L',
    nameRu: 'Контактный инсектицид против коробочного червя, 5 л',
    nameUz: 'Paxta qurtiga qarshi kontakt insektitsid, 5 l',
    nameUzCyrl: 'Пахта қуртига қарши контакт инсектицид, 5 л',
    priceUzs: 396_000,
    region: 'Andijon',
    stockQuantity: 145,
    supplier: suppliers.agroKimyo,
    unit: '5 l',
  },
  {
    catalogNumber: 34,
    category: 'pesticide',
    description: 'Гербицид против двудольных сорняков в посевах пшеницы и ячменя. Норма 0,6–0,8 л/га.',
    images: [photo('knapsack-sprayer')],
    name: 'Selective herbicide for cereals, 10 L',
    nameRu: 'Гербицид избирательного действия для зерновых, 10 л',
    nameUz: "Boshoqlilar uchun tanlab ta'sir etuvchi gerbitsid, 10 l",
    nameUzCyrl: 'Бошоқлилар учун танлаб таъсир этувчи гербицид, 10 л',
    priceUzs: 512_000,
    region: "Farg'ona",
    stockQuantity: 92,
    supplier: suppliers.buxoroTaminot,
    unit: '10 l',
  },
  {
    catalogNumber: 35,
    category: 'pesticide',
    description: 'Сера смачивающаяся для виноградников и плодовых садов. Мешок 25 кг, срок ожидания 3 дня.',
    images: [photo('pesticide-spraying')],
    name: 'Wettable sulphur for powdery mildew, 25 kg',
    nameRu: 'Сера смачивающаяся против мучнистой росы, 25 кг',
    nameUz: 'Un shudring kasalligiga qarshi namlanuvchi oltingugurt, 25 kg',
    nameUzCyrl: 'Ун шудринг касаллигига қарши намланувчи олтингугурт, 25 кг',
    priceUzs: 268_000,
    region: 'Samarqand',
    sampleAvailable: false,
    stockQuantity: 160,
    supplier: suppliers.samarqandBog,
    unit: '25 kg',
  },
];

const equipment: readonly DemoProductSeed[] = [
  {
    catalogNumber: 8,
    category: 'equipment',
    description:
      'Трактор 80 л.с., 2023 год, наработка 640 моточасов. Полный сервисный лист, гарантия поставщика 6 месяцев.',
    images: [photo('tractor-field')],
    name: 'Tractor TTZ-80, 2023',
    nameRu: 'Трактор ТТЗ-80, 2023',
    nameUz: 'Traktor TTZ-80, 2023',
    nameUzCyrl: 'Трактор ТТЗ-80, 2023',
    priceUzs: 268_000_000,
    region: "Farg'ona",
    stockQuantity: 3,
    supplier: suppliers.fargonaTexnika,
    unit: '1 pc',
  },
  {
    catalogNumber: 9,
    category: 'equipment',
    description: 'Навесной оборотный плуг, 3 корпуса, ширина захвата 1,05 м. Для тракторов от 60 л.с.',
    images: [photo('plough'), photo('tractor-field')],
    name: 'Reversible plough, 3 furrow',
    nameRu: 'Плуг оборотный, 3 корпуса',
    nameUz: 'Aylanuvchi plug, 3 korpus',
    nameUzCyrl: 'Айланувчи плуг, 3 корпус',
    priceUzs: 18_400_000,
    region: "Farg'ona",
    stockQuantity: 11,
    supplier: suppliers.fargonaTexnika,
    unit: '1 pc',
  },
  {
    catalogNumber: 10,
    category: 'equipment',
    description: 'Ручной опрыскиватель 16 л с телескопической штангой. Ремкомплект в комплекте.',
    images: [photo('knapsack-sprayer')],
    name: 'Knapsack sprayer, 16 L',
    nameRu: 'Опрыскиватель ранцевый, 16 л',
    nameUz: "Yelkada ko'tariladigan purkagich, 16 l",
    nameUzCyrl: 'Елкада кўтариладиган пуркагич, 16 л',
    priceUzs: 640_000,
    region: 'Toshkent',
    stockQuantity: 210,
    supplier: suppliers.fargonaTexnika,
    unit: '1 pc',
  },
  {
    catalogNumber: 11,
    category: 'irrigation',
    description: 'Комплект капельного орошения на 1 га: лента, фитинги, фильтростанция. Монтаж по договорённости.',
    images: [photo('drip-irrigation')],
    name: 'Drip irrigation kit, 1 ha',
    nameRu: 'Комплект капельного орошения, 1 га',
    nameUz: "Tomchilatib sug'orish to'plami, 1 ga",
    nameUzCyrl: 'Томчилатиб суғориш тўплами, 1 га',
    priceUzs: 12_900_000,
    region: 'Qashqadaryo',
    stockQuantity: 24,
    supplier: suppliers.qashqaSuv,
    unit: '1 set',
  },
  {
    catalogNumber: 12,
    category: 'irrigation',
    description: 'Дизельный насос 4”, подача 90 м³/ч, напор 32 м. Для поливных каналов и водоёмов.',
    images: [photo('irrigation-pump')],
    name: 'Diesel water pump 4”',
    nameRu: 'Дизельный водяной насос 4”',
    nameUz: 'Dizel suv nasosi 4”',
    nameUzCyrl: 'Дизел сув насоси 4”',
    priceUzs: 9_450_000,
    region: 'Qashqadaryo',
    stockQuantity: 7,
    supplier: suppliers.qashqaSuv,
    unit: '1 pc',
  },
  {
    catalogNumber: 13,
    category: 'equipment',
    description: 'Прицеп тракторный самосвальный 2ПТС-4, грузоподъёмность 4 т, б/у, состояние рабочее.',
    images: [photo('farm-trailer')],
    name: 'Tipping trailer 2PTS-4, used',
    nameRu: 'Прицеп самосвальный 2ПТС-4, б/у',
    nameUz: "O'zi yuk tushiruvchi tirkama 2PTS-4",
    nameUzCyrl: 'Ўзи юк туширувчи тиркама 2ПТС-4',
    priceUzs: 21_700_000,
    region: 'Jizzax',
    stockQuantity: 2,
    supplier: suppliers.fargonaTexnika,
    unit: '1 pc',
  },
  {
    catalogNumber: 36,
    category: 'equipment',
    description: 'Культиватор навесной для сплошной обработки, 9 стоек, рабочая ширина 2,6 м. Для тракторов от 80 л.с.',
    images: [photo('cultivator')],
    name: 'Mounted stubble cultivator, 2.6 m',
    nameRu: 'Культиватор навесной, 2,6 м',
    nameUz: 'Osma kultivator, 2,6 m',
    nameUzCyrl: 'Осма култиватор, 2,6 м',
    priceUzs: 21_600_000,
    region: 'Toshkent',
    stockQuantity: 6,
    supplier: suppliers.toshkentAgroservis,
    unit: '1 pc',
  },
  {
    catalogNumber: 37,
    category: 'equipment',
    description:
      'Комбайн с жаткой 6 м, наработка 1 840 моточасов, бункер 6,5 м³. Диагностика и сервисный лист прилагаются.',
    images: [photo('combine-harvester'), photo('wheat-grain')],
    name: 'Grain combine harvester, 2019',
    nameRu: 'Зерноуборочный комбайн, 2019',
    nameUz: "Don o'rish kombayni, 2019",
    nameUzCyrl: 'Дон ўриш комбайни, 2019',
    priceUzs: 685_000_000,
    region: 'Sirdaryo',
    stockQuantity: 2,
    supplier: suppliers.toshkentAgroservis,
    unit: '1 pc',
  },
  {
    catalogNumber: 38,
    category: 'equipment',
    description: 'Пневматическая сеялка точного высева на 12 рядов, регулировка нормы без замены дисков.',
    images: [photo('seed-drill')],
    name: 'Pneumatic seed drill, 12 rows',
    nameRu: 'Сеялка пневматическая, 12 рядов',
    nameUz: 'Pnevmatik seyalka, 12 qator',
    nameUzCyrl: 'Пневматик сеялка, 12 қатор',
    priceUzs: 74_500_000,
    region: 'Sirdaryo',
    stockQuantity: 3,
    supplier: suppliers.toshkentAgroservis,
    unit: '1 pc',
  },
  {
    catalogNumber: 39,
    category: 'equipment',
    description: 'Мотоблок бензиновый 7 л.с. с фрезой и окучником. Для приусадебных участков и теплиц.',
    images: [photo('power-tiller')],
    name: 'Walk-behind power tiller, 7 hp petrol',
    nameRu: 'Мотоблок бензиновый, 7 л.с.',
    nameUz: 'Benzinli motoblok, 7 ot kuchi',
    nameUzCyrl: 'Бензинли мотоблок, 7 от кучи',
    priceUzs: 9_800_000,
    region: 'Namangan',
    stockQuantity: 18,
    supplier: suppliers.toshkentAgroservis,
    unit: '1 pc',
  },
  {
    catalogNumber: 40,
    category: 'equipment',
    description: 'Прицепной опрыскиватель 600 л, штанга 12 м, гидравлическое сложение. Для тракторов от 50 л.с.',
    images: [photo('pesticide-spraying'), photo('tractor-field')],
    name: 'Trailed field sprayer, 600 L',
    nameRu: 'Опрыскиватель прицепной, 600 л',
    nameUz: 'Tirkama purkagich, 600 l',
    nameUzCyrl: 'Тиркама пуркагич, 600 л',
    priceUzs: 42_900_000,
    region: "Farg'ona",
    stockQuantity: 4,
    supplier: suppliers.toshkentAgroservis,
    unit: '1 pc',
  },
  {
    catalogNumber: 41,
    category: 'equipment',
    description:
      'Самоходная хлопкоуборочная машина, наработка 2 100 моточасов. Шпиндельные барабаны заменены в межсезонье.',
    images: [photo('cotton-harvester'), photo('cotton-field')],
    name: 'Cotton harvester, self-propelled, used',
    nameRu: 'Хлопкоуборочная машина самоходная, б/у',
    nameUz: "O'zi yurar paxta terish mashinasi, ishlatilgan",
    nameUzCyrl: 'Ўзи юрар пахта териш машинаси, ишлатилган',
    priceUzs: 412_000_000,
    region: 'Andijon',
    stockQuantity: 1,
    supplier: suppliers.fargonaTexnika,
    unit: '1 pc',
  },
  {
    catalogNumber: 42,
    category: 'equipment',
    description: 'Дисковая борона навесная, ширина захвата 2,4 м, диски 510 мм. Для предпосевной обработки.',
    images: [photo('disc-harrow')],
    name: 'Disc harrow, 2.4 m',
    nameRu: 'Борона дисковая, 2,4 м',
    nameUz: 'Diskli borona, 2,4 m',
    nameUzCyrl: 'Дискли борона, 2,4 м',
    priceUzs: 19_800_000,
    region: 'Jizzax',
    stockQuantity: 5,
    supplier: suppliers.fargonaTexnika,
    unit: '1 pc',
  },
  {
    catalogNumber: 43,
    category: 'equipment',
    description: 'Рулонный пресс-подборщик для люцерны и соломы, диаметр рулона 1,2 м, обмотка шпагатом.',
    images: [photo('alfalfa-bales')],
    name: 'Round hay baler, trailed',
    nameRu: 'Пресс-подборщик рулонный, прицепной',
    nameUz: 'Tirkama rulonli pichan presslash mashinasi',
    nameUzCyrl: 'Тиркама рулонли пичан пресслаш машинаси',
    priceUzs: 96_400_000,
    region: 'Samarqand',
    stockQuantity: 2,
    supplier: suppliers.fargonaTexnika,
    unit: '1 pc',
  },
  {
    catalogNumber: 44,
    category: 'equipment',
    description: 'Трёхслойная тепличная плёнка 150 мкм, рукав 8 м, рулон 50 м. Стабилизация к УФ на 3 сезона.',
    images: [photo('greenhouse-film')],
    name: 'Greenhouse film, 150 micron, 8 m wide',
    nameRu: 'Плёнка тепличная, 150 мкм, ширина 8 м',
    nameUz: 'Issiqxona plyonkasi, 150 mikron, kengligi 8 m',
    nameUzCyrl: 'Иссиқхона плёнкаси, 150 микрон, кенглиги 8 м',
    priceUzs: 1_180_000,
    region: 'Namangan',
    stockQuantity: 140,
    supplier: suppliers.namanganIssiqxona,
    unit: '1 roll',
  },
  {
    catalogNumber: 45,
    category: 'equipment',
    description: 'Кассеты под рассаду томата и перца, 105 ячеек, полистирол. Партия распродана до следующей поставки.',
    images: [photo('tomato-greenhouse')],
    name: 'Seedling trays, 105 cells, 100 pcs',
    nameRu: 'Кассеты для рассады, 105 ячеек, 100 шт',
    nameUz: "Ko'chat kassetalari, 105 uyali, 100 dona",
    nameUzCyrl: 'Кўчат кассеталари, 105 уяли, 100 дона',
    priceUzs: 890_000,
    region: 'Namangan',
    stockQuantity: 0,
    supplier: suppliers.namanganIssiqxona,
    unit: '1 pack',
  },
  {
    catalogNumber: 46,
    category: 'irrigation',
    description: 'Дождевальная машина круговая, вылет 240 м, б/у. Монтаж и пусконаладка по договорённости.',
    images: [photo('sprinkler-irrigation')],
    name: 'Centre pivot irrigation machine, 240 m, used',
    nameRu: 'Дождевальная машина круговая, 240 м, б/у',
    nameUz: "Aylanma yomg'irlatish mashinasi, 240 m, ishlatilgan",
    nameUzCyrl: 'Айланма ёмғирлатиш машинаси, 240 м, ишлатилган',
    priceUzs: 340_000_000,
    region: 'Qashqadaryo',
    stockQuantity: 4,
    supplier: suppliers.qashqaSuv,
    unit: '1 set',
  },
  {
    catalogNumber: 47,
    category: 'irrigation',
    description: 'Полиэтиленовая труба ПНД 110 мм на 10 атмосфер, отрезок 6 м. Для магистралей капельного орошения.',
    images: [photo('hdpe-pipes')],
    name: 'HDPE main pipe 110 mm, PN10, 6 m',
    nameRu: 'Труба ПНД 110 мм, PN10, 6 м',
    nameUz: 'HDPE magistral quvur 110 mm, PN10, 6 m',
    nameUzCyrl: 'HDPE магистрал қувур 110 мм, PN10, 6 м',
    priceUzs: 640_000,
    region: 'Buxoro',
    stockQuantity: 220,
    supplier: suppliers.qashqaSuv,
    unit: '1 pc',
  },
  {
    catalogNumber: 48,
    category: 'irrigation',
    description: 'Погружной скважинный насос 5,5 кВт, подача 12 м³/ч, напор 78 м. Для вертикального дренажа и полива.',
    images: [photo('irrigation-pump')],
    name: 'Submersible borehole pump, 5.5 kW',
    nameRu: 'Насос скважинный погружной, 5,5 кВт',
    nameUz: 'Quduq uchun suvga botadigan nasos, 5,5 kVt',
    nameUzCyrl: 'Қудуқ учун сувга ботадиган насос, 5,5 кВт',
    priceUzs: 11_700_000,
    region: 'Xorazm',
    stockQuantity: 9,
    supplier: suppliers.qashqaSuv,
    unit: '1 pc',
  },
  {
    catalogNumber: 49,
    category: 'irrigation',
    description: 'Капельная лента 16 мм с эмиттерами через 0,3 м, расход 1,6 л/ч. Бухта 1000 м.',
    images: [photo('drip-irrigation')],
    name: 'Drip tape 16 mm, 0.3 m spacing, 1000 m',
    nameRu: 'Капельная лента 16 мм, шаг 0,3 м, 1000 м',
    nameUz: 'Tomchilatuvchi lenta 16 mm, qadami 0,3 m, 1000 m',
    nameUzCyrl: 'Томчилатувчи лента 16 мм, қадами 0,3 м, 1000 м',
    priceUzs: 1_460_000,
    region: 'Surxondaryo',
    stockQuantity: 320,
    supplier: suppliers.qashqaSuv,
    unit: '1 roll',
  },
  {
    catalogNumber: 50,
    category: 'irrigation',
    description: 'Дисковая фильтростанция 2 дюйма на 1 га, степень фильтрации 130 мкм, промывка вручную.',
    images: [],
    name: 'Disc filter station 2”, 1 ha',
    nameRu: 'Фильтростанция дисковая 2”, 1 га',
    nameUz: 'Diskli filtr stansiyasi 2”, 1 ga',
    nameUzCyrl: 'Дискли филтр стансияси 2”, 1 га',
    priceUzs: 4_850_000,
    region: "Qoraqalpog'iston",
    stockQuantity: 12,
    supplier: suppliers.qashqaSuv,
    unit: '1 pc',
  },
  {
    catalogNumber: 51,
    category: 'equipment',
    description: 'Пластиковые ящики 20 кг под абрикос, черешню и виноград, штабелируемые. Партия 200 штук.',
    images: [photo('uzbek-bazaar')],
    name: 'Fruit crates, 20 kg, 200 pcs',
    nameRu: 'Ящики для фруктов, 20 кг, 200 шт',
    nameUz: 'Meva yashiklari, 20 kg, 200 dona',
    nameUzCyrl: 'Мева яшиклари, 20 кг, 200 дона',
    priceUzs: 2_100_000,
    region: 'Surxondaryo',
    stockQuantity: 90,
    supplier: suppliers.surxonMeva,
    unit: '1 pack',
  },
];

const produce: readonly DemoProductSeed[] = [
  {
    catalogNumber: 14,
    category: 'other',
    description: 'Столовый сорт, калибр 22+, урожай 2026. Хранение в холодильной камере, готово к отгрузке.',
    images: [photo('table-grapes')],
    name: 'Table grapes “Husayni”, grade 1',
    nameRu: 'Виноград столовый «Хусайни», 1 сорт',
    nameUz: 'Uzum «Husayni», 1-navli',
    nameUzCyrl: 'Узум «Ҳусайни», 1-навли',
    priceUzs: 14_800_000,
    region: 'Samarqand',
    stockQuantity: 36,
    supplier: suppliers.samarqandBog,
    unit: '1 t',
  },
  {
    catalogNumber: 15,
    category: 'other',
    description: 'Сушёный урюк без сердцевины, влажность 18%, фасовка по 10 кг. Экспортное качество.',
    images: [photo('dried-apricots')],
    name: 'Dried apricot, export grade',
    nameRu: 'Урюк сушёный, экспортный',
    nameUz: "Quritilgan o'rik, eksport sifati",
    nameUzCyrl: 'Қуритилган ўрик, экспорт сифати',
    priceUzs: 42_500_000,
    region: "Farg'ona",
    stockQuantity: 18,
    supplier: suppliers.xorazmHosil,
    unit: '1 t',
  },
  {
    catalogNumber: 16,
    category: 'other',
    description: 'Картофель продовольственный, калибр 45–70 мм, сорт Ривьера. Минимальная партия 5 т.',
    images: [photo('ware-potatoes')],
    name: 'Ware potato “Riviera”',
    nameRu: 'Картофель продовольственный «Ривьера»',
    nameUz: 'Oziq-ovqat kartoshkasi «Riviera»',
    nameUzCyrl: 'Озиқ-овқат картошкаси «Ривьера»',
    priceUzs: 4_200_000,
    region: 'Toshkent',
    stockQuantity: 120,
    supplier: suppliers.dehqonBozor,
    unit: '1 t',
  },
  {
    catalogNumber: 17,
    category: 'other',
    description: 'Лук репчатый жёлтый, калибр 60+, урожай текущего сезона. Сетка 25 кг.',
    images: [photo('yellow-onions'), photo('uzbek-bazaar')],
    name: 'Yellow onion, 60+ mm',
    nameRu: 'Лук репчатый жёлтый, 60+ мм',
    nameUz: 'Sariq piyoz, 60+ mm',
    nameUzCyrl: 'Сариқ пиёз, 60+ мм',
    priceUzs: 2_950_000,
    region: 'Xorazm',
    stockQuantity: 240,
    supplier: suppliers.xorazmHosil,
    unit: '1 t',
  },
  {
    // Deliberately sold out: it is the row that exercises the out-of-stock badge
    // and the "in stock" filter. The listing itself stays active, because the
    // catalog endpoints only ever publish active rows.
    catalogNumber: 18,
    category: 'other',
    description: 'Дыня «Гурвак», средний вес плода 4,5 кг. Отгрузка партиями от 3 тонн, самовывоз.',
    images: [photo('melon')],
    name: 'Melon “Gurvak”',
    nameRu: 'Дыня «Гурвак»',
    nameUz: "Qovun «G'urvak»",
    nameUzCyrl: 'Қовун «Ғурвак»',
    priceUzs: 5_600_000,
    region: 'Xorazm',
    stockQuantity: 0,
    supplier: suppliers.xorazmHosil,
    unit: '1 t',
  },
  {
    catalogNumber: 19,
    category: 'other',
    description: 'Хлопковый жмых, протеин 38%, для кормовых смесей. Отгрузка навалом или в биг-бэгах.',
    // Deliberately without photographs: it is the row that keeps the
    // category-illustration fallback exercised on a real seeded listing.
    images: [],
    name: 'Cottonseed cake, 38% protein',
    nameRu: 'Хлопковый жмых, протеин 38%',
    nameUz: 'Paxta kunjarasi, 38% protein',
    nameUzCyrl: 'Пахта кунжараси, 38% протеин',
    priceUzs: 3_400_000,
    region: 'Andijon',
    stockQuantity: 64,
    supplier: suppliers.dehqonBozor,
    unit: '1 t',
  },
  {
    catalogNumber: 52,
    category: 'other',
    description: 'Арбуз урожая текущего сезона, средняя масса 9 кг. Отгрузка партиями от 5 тонн, самовывоз.',
    images: [photo('watermelon-field')],
    name: 'Watermelon, field grade',
    nameRu: 'Арбуз продовольственный',
    nameUz: 'Tarvuz, oziq-ovqat navi',
    nameUzCyrl: 'Тарвуз, озиқ-овқат нави',
    priceUzs: 2_450_000,
    region: 'Xorazm',
    stockQuantity: 180,
    supplier: suppliers.xorazmDehqon,
    unit: '1 t',
  },
  {
    catalogNumber: 53,
    category: 'other',
    description: 'Рис шлифованный длиннозёрный, целое зерно не менее 92%. Фасовка мешки 25 кг.',
    images: [photo('rice-paddy')],
    name: 'Rice, long grain, milled',
    nameRu: 'Рис длиннозёрный, шлифованный',
    nameUz: 'Guruch, uzun donli, silliqlangan',
    nameUzCyrl: 'Гуруч, узун донли, силлиқланган',
    priceUzs: 11_200_000,
    region: "Qoraqalpog'iston",
    stockQuantity: 90,
    supplier: suppliers.sirdaryoDon,
    unit: '1 t',
  },
  {
    catalogNumber: 54,
    category: 'other',
    description: 'Кукуруза на фураж, влажность 14%, сорная примесь до 2%. Партия текущего урожая распродана.',
    images: [photo('maize-cobs')],
    name: 'Maize grain, feed quality',
    nameRu: 'Кукуруза фуражная',
    nameUz: "Makkajo'xori doni, yem sifati",
    nameUzCyrl: 'Маккажўхори дони, ем сифати',
    priceUzs: 3_650_000,
    region: 'Sirdaryo',
    stockQuantity: 0,
    supplier: suppliers.sirdaryoDon,
    unit: '1 t',
  },
  {
    catalogNumber: 55,
    category: 'other',
    description: 'Гранат столовый, калибр 250+ г, урожай текущего сезона. Укладка в ящики по 10 кг.',
    images: [photo('pomegranate')],
    name: 'Pomegranate, calibre 250+',
    nameRu: 'Гранат, калибр 250+',
    nameUz: 'Anor, kalibr 250+',
    nameUzCyrl: 'Анор, калибр 250+',
    priceUzs: 9_800_000,
    region: 'Surxondaryo',
    stockQuantity: 42,
    supplier: suppliers.surxonMeva,
    unit: '1 t',
  },
  {
    catalogNumber: 56,
    category: 'other',
    description: 'Хурма шоколадного типа, плод 180–220 г, без вязкости. Партия этого сезона реализована.',
    images: [photo('persimmon')],
    name: 'Persimmon, chocolate type',
    nameRu: 'Хурма шоколадная',
    nameUz: 'Shokolad turidagi xurmo',
    nameUzCyrl: 'Шоколад туридаги хурмо',
    priceUzs: 8_600_000,
    region: 'Surxondaryo',
    stockQuantity: 0,
    supplier: suppliers.surxonMeva,
    unit: '1 t',
  },
  {
    catalogNumber: 57,
    category: 'other',
    description: 'Абрикос столовый, калибр 35–45 мм, охлаждение после сбора. Ящики 5 кг.',
    images: [photo('fresh-apricots')],
    name: 'Fresh apricot, table grade',
    nameRu: 'Абрикос свежий, столовый',
    nameUz: "Yangi o'rik, iste'mol navi",
    nameUzCyrl: 'Янги ўрик, истеъмол нави',
    priceUzs: 12_600_000,
    region: "Farg'ona",
    stockQuantity: 58,
    supplier: suppliers.surxonMeva,
    unit: '1 t',
  },
  {
    catalogNumber: 58,
    category: 'other',
    description: 'Чеснок озимый сухой, калибр 50+ мм, шейка обрезана. Сетка 10 кг.',
    images: [photo('garlic-bulbs')],
    name: 'Garlic, dry, calibre 50+',
    nameRu: 'Чеснок сухой, калибр 50+',
    nameUz: 'Sarimsoq, quruq, kalibr 50+',
    nameUzCyrl: 'Саримсоқ, қуруқ, калибр 50+',
    priceUzs: 16_900_000,
    region: 'Namangan',
    stockQuantity: 34,
    supplier: suppliers.surxonMeva,
    unit: '1 t',
  },
  {
    catalogNumber: 59,
    category: 'other',
    description: 'Кишмиш тёмный, сушка на солнце, влажность 16%, без сернистой обработки. Ящики 12,5 кг.',
    images: [photo('raisins')],
    name: 'Dark raisins, sun-dried',
    nameRu: 'Кишмиш тёмный, сушёный на солнце',
    nameUz: 'Quyoshda quritilgan qora kishmish',
    nameUzCyrl: 'Қуёшда қуритилган қора кишмиш',
    priceUzs: 28_400_000,
    region: 'Samarqand',
    stockQuantity: 26,
    supplier: suppliers.xorazmHosil,
    unit: '1 t',
  },
  {
    catalogNumber: 60,
    category: 'other',
    description: 'Сено люцерны второго укоса в рулонах по 300 кг, влажность 15%. Хранение под навесом.',
    images: [photo('alfalfa-bales')],
    name: 'Alfalfa hay, second cut, bales',
    nameRu: 'Сено люцерны, второй укос, в рулонах',
    nameUz: "Beda pichani, ikkinchi o'rim, rulonlarda",
    nameUzCyrl: 'Беда пичани, иккинчи ўрим, рулонларда',
    priceUzs: 1_850_000,
    region: 'Jizzax',
    stockQuantity: 240,
    supplier: suppliers.xorazmDehqon,
    unit: '1 t',
  },
  {
    catalogNumber: 61,
    category: 'other',
    description: 'Маш продовольственный, калиброванный, примесь до 1%. Мешки 50 кг.',
    images: [photo('mung-beans')],
    name: 'Mung bean, food grade',
    nameRu: 'Маш продовольственный',
    nameUz: 'Mosh, oziq-ovqat sifati',
    nameUzCyrl: 'Мош, озиқ-овқат сифати',
    priceUzs: 19_400_000,
    region: "Farg'ona",
    stockQuantity: 46,
    supplier: suppliers.xorazmDehqon,
    unit: '1 t',
  },
  {
    catalogNumber: 62,
    category: 'other',
    description: 'Морковь мытая, калибр 30–60 мм, для зимнего хранения. Сетка 20 кг.',
    images: [photo('carrots')],
    name: 'Carrot, storage grade',
    nameRu: 'Морковь продовольственная, лежкая',
    nameUz: 'Sabzi, saqlash uchun',
    nameUzCyrl: 'Сабзи, сақлаш учун',
    priceUzs: 3_100_000,
    region: 'Toshkent',
    stockQuantity: 150,
    supplier: suppliers.dehqonBozor,
    unit: '1 t',
  },
  {
    catalogNumber: 63,
    category: 'other',
    description: 'Томат тепличный зимнего оборота, плод 130–150 г, укладка в ящики 6 кг.',
    images: [photo('tomato-fruit'), photo('tomato-greenhouse')],
    name: 'Greenhouse tomato, table grade',
    nameRu: 'Томат тепличный, столовый',
    nameUz: "Issiqxona pomidori, iste'mol navi",
    nameUzCyrl: 'Иссиқхона помидори, истеъмол нави',
    priceUzs: 13_400_000,
    region: "Farg'ona",
    stockQuantity: 62,
    supplier: suppliers.fargonaDehqon,
    unit: '1 t',
  },
];

const supplierId = (name: string): string => `demo-supplier-${name.toLowerCase().replaceAll(/[^a-z0-9]+/gu, '-')}`;

/**
 * Whether a demo listing offers a sample. A buyer can ask for a handful of seed
 * or a sack of fertilizer before committing to a truckload, but nobody samples a
 * tractor, so machinery and irrigation kits offer none.
 */
const sampleAvailableFor = (category: ProductCategory): boolean =>
  category !== 'equipment' && category !== 'irrigation';

const toProduct = (seed: DemoProductSeed): Product => ({
  category: seed.category,
  createdAt,
  description: seed.description,
  id: demoProductId(seed.catalogNumber),
  images: [...seed.images],
  name: seed.name,
  nameRu: seed.nameRu,
  nameUz: seed.nameUz,
  nameUzCyrl: seed.nameUzCyrl,
  priceUzs: seed.priceUzs,
  region: seed.region,
  sampleAvailable: seed.sampleAvailable ?? sampleAvailableFor(seed.category),
  status: 'active',
  stockQuantity: seed.stockQuantity,
  supplierId: supplierId(seed.supplier),
  supplierName: seed.supplier,
  unit: seed.unit,
  updatedAt,
});

const catalog: readonly DemoProductSeed[] = [...seeds, ...equipment, ...produce];

/**
 * Two rows sharing a catalog number resolve to one uuid, so the second silently
 * replaces the first everywhere the id is referenced — in the seeded catalog, in
 * its publication, and in any contract line quoting it. Failing here names the
 * collision instead of leaving a listing quietly missing.
 */
const duplicateCatalogNumber = catalog
  .map((seed) => seed.catalogNumber)
  .find((value, index, all) => all.indexOf(value) !== index);

if (duplicateCatalogNumber !== undefined) {
  throw new Error(`Demo catalog reuses catalog number ${duplicateCatalogNumber}; every row needs its own.`);
}

export const DemoProducts: readonly Product[] = catalog.map(toProduct);

/** Mirrors the repository filter so demo and live reads answer a query alike. */
export function filterDemoProducts(filter?: { category?: ProductCategory; region?: string }): Product[] {
  return DemoProducts.filter(
    (product) =>
      (!filter?.category || product.category === filter.category) &&
      (!filter?.region || product.region === filter.region),
  );
}

/** Resolves a demo listing by id, so product detail works on demo content too. */
export const findDemoProduct = (id: string): Product | undefined => DemoProducts.find((product) => product.id === id);

/** Whether an id belongs to the demo dataset rather than a tenant's own catalog. */
export const isDemoProductId = (id: string): boolean => DemoProducts.some((product) => product.id === id);
