// Generated by `pnpm nrb setup`. Do not edit by hand.
import { Global, Module } from '@nestjs/common';
import { RedisModule } from '@app/backend-common-redis';
import { S3Module } from '@app/backend-common-s3';
import { MarketplaceContractNotificationDeliveryModule } from '@app/backend-feature-agritech-main';
import { NotificationMainModule } from '@app/backend-feature-notification-main';
import { PostgresMainModule } from '@app/backend-postgres-main';
import { AgriTechPostgresModule } from '@app/backend-postgres-main-agritech';
import { AuthPostgresModule } from '@app/backend-postgres-main-auth';
import { FeatureFlagsPostgresModule } from '@app/backend-postgres-main-feature-flags';
import { NotificationPostgresModule } from '@app/backend-postgres-main-notification';

@Global()
@Module({
  imports: [
    AgriTechPostgresModule,
    AuthPostgresModule,
    FeatureFlagsPostgresModule,
    MarketplaceContractNotificationDeliveryModule,
    NotificationMainModule.forRoot({ enableScheduler: true, exposeHttp: false }),
    NotificationPostgresModule,
    PostgresMainModule.forRoot(),
    RedisModule.forRoot(),
    S3Module.forRoot(),
  ],
  exports: [
    AgriTechPostgresModule,
    AuthPostgresModule,
    FeatureFlagsPostgresModule,
    MarketplaceContractNotificationDeliveryModule,
    NotificationMainModule,
    NotificationPostgresModule,
    PostgresMainModule,
    RedisModule,
    S3Module,
  ],
})
export class NotificationSchedulerCapabilitiesModule {}
